development:
  clients:
    default:
      uri: mongodb+srv://makersnomads@gmail.com:nomads4life@Cluster0.mongodb.net/makers_bnb?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5