development:
  clients:
    default:
      uri: mongodb://makersnomads%40gmail.com:nomads4life@cluster0.mongodb.net:27017/makers_bnb?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5